name: Build Workflow

on:
  workflow_call:
    inputs:
      semVer:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  buildApplicationJob:
    name: Build .NET Applciations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build Projects
        working-directory: ./src
        run: |
          dotnet build ./PaTsa.Conference.App.Api.sln \
            --configuration Release \
            --nologo \
            /p:Version=${{ inputs.semVer }}

      - name: Run Unit Tests
        working-directory: ./src
        run: |
          dotnet test ./PaTsa.Conference.App.Api.UnitTests/PaTsa.Conference.App.Api.UnitTests.csproj \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --filter "TestCategory=UnitTest" \
            --nologo \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover

      - name: Collect Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/PaTsa.Conference.App.Api.UnitTests/coverage.opencover.xml

      - name: Publish Web API
        working-directory: ./src
        run: |
          dotnet publish ./PaTsa.Conference.App.Api.WebApi/PaTsa.Conference.App.Api.WebApi.csproj \
            --configuration Release \
            --no-build \
            --output ${{ runner.temp }}/PaTsa.Conference.App.Api.WebApi \
            --nologo

      - uses: actions/upload-artifact@v3
        name: Upload Published Web API App
        with:
          name: web-api
          path: ${{ runner.temp }}/PaTsa.Conference.App.Api.WebApi
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        name: Upload Code Coverage to Artifacts
        with:
          name: code-coverage
          path: ./src/PaTsa.Conference.App.Api.UnitTests/coverage.opencover.xml
          if-no-files-found: error