name: Continuous Delivery Workflow

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  gitVersionJob:
    name: CD - GitVersion Workflow
    uses: ./.github/workflows/gitversion-reusable-workflow.yml

  buildApplicationJob:
    name: CD - Build Workflow
    needs: gitVersionJob
    uses: ./.github/workflows/build-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit

  # TODO: Make this a deploy job and deploy to production
  # terraformApplyJob:
  #   name: CD - Terraform Apply Workflow
  #   needs: gitVersionJob
  #   uses: ./.github/workflows/terraform-apply-reusable-workflow.yml
  #   secrets: inherit

  deployApplicationJob:
    name: CD - Deploy Workflow
    # needs: [buildApplicationJob, terraformApplyJob]
    needs: [buildApplicationJob]
    uses: ./.github/workflows/deploy-reusable-workflow.yml
    with:
      azureAppName: pa-tsa-conference-app-api-app
      environment: production
    secrets: inherit

  tagRepoJob:
    name: CD - Tag Repo Workflow
    needs: [gitVersionJob, deployApplicationJob]
    uses: ./.github/workflows/tag-repo-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit
