name: continuous-integration-workflow

# Build on every push (regardless of branch) for code changes
# Build on PR to ensure the merge is good for code changes
# Allow manual builds
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/continuous-integration-workflow.yml'
      - '.github/workflows/reusable/**'
      - 'src/**'

  workflow_dispatch:

jobs:
  gitVersionJob:
    uses: ./.github/workflows/reusable/gitversion-reusable-workflow.yml

  buildApplicationJob:
    needs: gitVersionJob
    uses: ./.github/workflow/reusable/build-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit

  verifyCodeStyleJob:
    uses: ./.github/workflow/reusable/verify-code-style-reusable-workflow.yml
