name: Continuous Integration Workflow

# Build on every push (regardless of branch) for code changes
# Build on PR to ensure the merge is good for code changes
# Allow manual builds
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/continuous-integration-workflow.yml'
      - '.github/workflows/**-reusable-workflow.yml'
      - 'src/**'

  workflow_dispatch:

jobs:
  gitVersionJob:
    name: CI - GitVersion Workflow
    uses: ./.github/workflows/gitversion-reusable-workflow.yml

  buildApplicationJob:
    name: CI - Build Workflow
    needs: gitVersionJob
    uses: ./.github/workflows/build-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit

  verifyCodeStyleJob:
    name: CI - Verify Code Style Workflow
    uses: ./.github/workflows/verify-code-style-reusable-workflow.yml
