name: Continuous Delivery Workflow

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  gitVersionJob:
    name: CD - GitVersion Workflow
    uses: ./.github/workflows/gitversion-reusable-workflow.yml

  buildApplicationJob:
    name: CD - Build Workflow
    needs: gitVersionJob
    uses: ./.github/workflows/build-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit

  terraformApplyJob:
    name: CD - Terraform Apply Workflow
    needs: gitVersionJob
    uses: ./.github/workflows/terraform-apply-reusable-workflow.yml
    secrets: inherit

  tagRepoJob:
    name: CD - Tag Repo Workflow
    needs: [gitVersionJob, buildApplicationJob, terraformApplyJob]
    uses: ./.github/workflows/tag-repo-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit