name: Deploy Workflow

on:
  workflow_call:
    inputs:
      azureAppName:
        required: true
        type: string
        description: The name of the Azure App Service the application should be deployed to
      environment:
        required: true
        type: string
        description: The name of the environment the deploy the application should be deployed to

jobs:
  deployJob:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: web-api
          path: web-api

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.azureAppName }}
          package: web-api
