name: Deploy Workflow

on:
  workflow_call:
    inputs:
      azureAppName:
        required: true
        type: string
        description: The name of the Azure App Service the application should be deployed to
      environment:
        required: true
        type: string
        description: The name of the environment the deploy the application should be deployed to

jobs:
  deployJob:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: web-api

      - run: |
          pwd
          ls -l /home/runner/work/pa-tsa-conference-app-api/pa-tsa-conference-app-api

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az account show
          az webapp list --query "[*].name"

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.azureAppName }}
          package: web-api.zip
