name: GitVersion Workflow

on:
  workflow_call:
    outputs:
      major: ${{ jobs.gitVersionJob.outputs.major }}
      minor: ${{ jobs.gitVersionJob.outputs.minor }}
      patch: ${{ jobs.gitVersionJob.outputs.patch }}
      majorMinor: ${{ jobs.gitVersionJob.outputs.major }}.${{ jobs.gitVersionJob.outputs.minor }}
      releaseLabel: ${{ jobs.gitVersionJob.outputs.major }}.${{ jobs.gitVersionJob.outputs.minor }}.${{ jobs.gitVersionJob.outputs.patch }}${{ jobs.gitVersionJob.outputs.prereleaselabelwithdash }}
      majorMinorReleaseLabel: ${{ jobs.gitVersionJob.outputs.major }}.${{ jobs.gitVersionJob.outputs.minor }}${{ jobs.gitVersionJob.outputs.prereleaselabelwithdash }}
      majorReleaseLabel: ${{ jobs.gitVersionJob.outputs.major }}${{ jobs.gitVersionJob.outputs.prereleaselabelwithdash }}
      semVer: ${{ jobs.gitVersionJob.outputs.semver }}
      shorSha: ${{ jobs.gitVersionJob.outputs.shortSha }}

jobs:
  gitVersionJob:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.execute-gitversion-step.outputs.major }}
      minor: ${{ steps.execute-gitversion-step.outputs.minor }}
      patch: ${{ steps.execute-gitversion-step.outputs.patch }}
      majorMinor: ${{ steps.execute-gitversion-step.outputs.major }}.${{ steps.execute-gitversion-step.outputs.minor }}
      releaseLabel: ${{ steps.execute-gitversion-step.outputs.major }}.${{ steps.execute-gitversion-step.outputs.minor }}.${{ steps.execute-gitversion-step.outputs.patch }}${{ steps.execute-gitversion-step.outputs.prereleaselabelwithdash }}
      majorMinorReleaseLabel: ${{ steps.execute-gitversion-step.outputs.major }}.${{ steps.execute-gitversion-step.outputs.minor }}${{ steps.execute-gitversion-step.outputs.prereleaselabelwithdash }}
      majorReleaseLabel: ${{ steps.execute-gitversion-step.outputs.major }}${{ steps.execute-gitversion-step.outputs.prereleaselabelwithdash }}
      semVer: ${{ steps.execute-gitversion-step.outputs.semver }}
      shorSha: ${{ steps.execute-gitversion-step.outputs.shortSha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        id: install-gitversion-step
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'
        
      - name: Execute GitVersion
        id: execute-gitversion-step
        uses: gittools/actions/gitversion/execute@v0.9.14