name: pr-workflow

on:
  pull_request:
    paths:
      - '.github/workflows/pr-workflow.yml'
      - '.github/workflows/**-reusable-workflow.yml'
      - 'src/**'
      - 'terraform/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  gitVersionJob:
    name: GitVersion Workflow
    uses: ./.github/workflows/gitversion-reusable-workflow.yml

  buildApplicationJob:
    name: Build Workflow
    needs: gitVersionJob
    uses: ./.github/workflows/build-reusable-workflow.yml
    with:
      semVer: ${{ needs.gitVersionJob.outputs.semVer }}
    secrets: inherit

  terraformPlanJob:
    name: Terraform Plan Workflow
    needs: gitVersionJob
    uses: ./.github/workflows/terraform-plan-reusable-workflow.yml
    secrets: inherit

  verifyCodeStyleJob:
    name: Verify Code Style Workflow
    uses: ./.github/workflows/verify-code-style-reusable-workflow.yml
  